// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Cell$ReactTemplate = require("./Cell.bs.js");

var component = ReasonReact.statelessComponent("Explore");

function make(dataString, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var hexList = $$Array.map((function (s) {
                      return "0x" + s;
                    }), dataString.split(" "));
              var capitalHexList = $$Array.to_list($$Array.map(Caml_format.caml_int_of_string, hexList));
              return React.createElement("div", {
                          style: {
                            height: "100%",
                            width: "100%"
                          }
                        }, ReasonReact.element(undefined, undefined, Cell$ReactTemplate.make(capitalHexList, /* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
