// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function splitAt(list, n) {
  var len = List.length(list);
  var min = len - n | 0;
  var _x = len;
  var _hd = /* [] */0;
  var _tl = /* [] */0;
  while(true) {
    var tl = _tl;
    var hd = _hd;
    var x = _x;
    if (x !== 0) {
      if (x > min) {
        _hd = /* :: */[
          List.nth(list, len - x | 0),
          hd
        ];
        _x = x - 1 | 0;
        continue ;
      } else {
        _tl = /* :: */[
          List.nth(list, len - x | 0),
          tl
        ];
        _x = x - 1 | 0;
        continue ;
      }
    } else {
      return /* tuple */[
              List.rev(hd),
              List.rev(tl)
            ];
    }
  };
}

exports.splitAt = splitAt;
/* No side effect */
